### ISSUE TITLE
The game crashes when i go on a server

### ISSUE THREAD

**Issue by sunias** [HGLabor/client-issues#34] opened 2020-12-17 08:21 UTC
so the game crashes when i get on a multiplayer server not always but often very very often the error is The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error

**Comment by F0Xde** [comment] 2020-12-17 08:49
Probably duplicate of #24 so already fixed, if not please always include the crash log.

**Closed as completed by F0Xde** 2020-12-17 08:49 UTC
Labels: duplicate
