### ISSUE TITLE
Game absturz

### ISSUE THREAD

**Issue by xaiyadev** [HGLabor/client-issues#32] opened 2020-12-17 07:46 UTC
Mein Game Crascht random

Fehler meldung: 
`The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: 255`

Log:
[crash-2020-12-17_08.42.32-client.txt](https://github.com/copyandexecute/noriskclient-issues/files/5707712/crash-2020-12-17_08.42.32-client.txt)

**Comment by F0Xde** [comment] 2020-12-17 08:43
Duplicate of #24

**Closed as completed by F0Xde** 2020-12-17 08:43 UTC
